# Base configs
baseurl: "https://shetu1994.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Ram Patra"
subtitle: "See the world through my eyes!"
author: "Hey there, my name is Shetu"
header:
 title: "Photography"
 subtitle: "by Shrishti Saha Shetu"
footer:
 name: "Hey there, my name is Shetu"
 bio: "I am a communication and a multimedia engineer.Photography is my hobby, so I adapted the following work to make one of my own website."
 github: "Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/obaddhota"
  instagram: "https://www.instagram.com/alternate_fiction/?hl=en"
#   dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/shrishti-shetu-fau/"
  github: "https://github.com/Shetu1994"

